server:
  port: 8080

security:
  oauth2:
    client:
      access-token-uri: https://dev-983347.okta.com/oauth2/default/v1/token
      user-authorization-uri: https://dev-983347.okta.com/oauth2/default/v1/authorize
      client-id: 0oael4x2cfpxJb1lw356
      scope: openid profile email
    resource:
      user-info-uri: https://dev-983347.okta.com/oauth2/default/v1/userinfo
      token-info-uri: https://dev-983347.okta.com/oauth2/default/v1/introspect
      prefer-token-info: false

spring:
  datasource:
    #SPRING_DATASOURCE_URL environment variable will be something like -> jdbc:sqlserver://MySqlServer\\MyInstance:1433;DatabaseName=MyDbName;
    url: jdbc:mysql://employees.cuc6jnhx12ca.us-west-1.rds.amazonaws.com/Employee
    username: master
    password: cmpe172project
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
